-- ============================================================================
-- Módulo de Ingestión por Correo (1.1) y Chat Web (1.2) — PostgreSQL
-- ============================================================================
-- Este script se ejecuta contra el esquema `solicitudes` (base `dovela_control`), que YA
-- EXISTE y ya está poblado (miembros_equipo, clientes, estatus, tipos_solicitud,
-- canales_solicitud, solicitudes, ...). No recrea nada de eso: solo agrega lo que este
-- módulo necesita para guardar adjuntos, la ruta del .md generado, y deduplicar correos.
-- ============================================================================

SET search_path TO solicitudes;

-- NOTA: miembros_equipo.correo_electronico está vacía para las 12 filas actuales (se
-- eliminó, en otra sesión, la columna que traía los emails de la importación CSV original,
-- sin hacer antes el backfill). El módulo de correo/chat resuelve "solicitante" buscando
-- por esa columna: hasta que se repueble manualmente, toda solicitud entrante quedará con
-- solicitante=NULL (comportamiento esperado y seguro, no un error).

-- 1) Adjuntos guardados en el NFS (real o simulado).
CREATE TABLE IF NOT EXISTS adjuntos (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_archivo       VARCHAR(500) NOT NULL,
  ruta_almacenamiento  VARCHAR(1000) NOT NULL,
  tipo_mime            VARCHAR(150),
  tamano_bytes         BIGINT,
  fecha_carga          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2) Relación N:M solicitud-adjunto.
CREATE TABLE IF NOT EXISTS solicitudes_adjuntos (
  solicitud_id BIGINT NOT NULL REFERENCES solicitudes(id),
  adjunto_id   BIGINT NOT NULL REFERENCES adjuntos(id),
  PRIMARY KEY (solicitud_id, adjunto_id)
);

CREATE INDEX IF NOT EXISTS idx_solicitudes_adjuntos_adjunto ON solicitudes_adjuntos(adjunto_id);

-- 3) Documento .md generado por solicitud (1:1).
CREATE TABLE IF NOT EXISTS solicitudes_md (
  solicitud_id     BIGINT PRIMARY KEY REFERENCES solicitudes(id),
  ruta_md          VARCHAR(1000) NOT NULL,
  fecha_generacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4) Deduplicación de correos ya procesados (idempotencia del worker ante reinicios).
CREATE TABLE IF NOT EXISTS emails_procesados (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_message_id VARCHAR(998) NOT NULL UNIQUE,
  solicitud_id     BIGINT REFERENCES solicitudes(id),
  fecha_procesado  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- IMPORTANTE: el solicitante de cada fila se resuelve buscando el email del remitente
-- (correo o chat) en miembros_equipo.correo_electronico. Si no hay match, la columna
-- "solicitante" de solicitudes queda NULL (permitido, ON DELETE SET NULL) para revisión
-- manual — no se inventa ni se crea un miembro nuevo.
-- ============================================================================
