-- Cambio de contraseña obligatorio en el primer acceso (o tras un reset del Scrum Master),
-- y recuperación de contraseña por correo electrónico.

ALTER TABLE miembros_equipo
    ADD COLUMN debe_cambiar_password boolean NOT NULL DEFAULT false;

CREATE TABLE tokens_reset_password (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    miembro_id  BIGINT NOT NULL REFERENCES miembros_equipo(id),
    token_hash  varchar(255) NOT NULL,
    expira_en   timestamptz NOT NULL,
    usado_en    timestamptz,
    creado_en   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_tokens_reset_password_hash ON tokens_reset_password(token_hash);
