-- Fase 1.20 — Notificaciones + menciones @ en comentarios
--
-- No existía ningún mecanismo de notificación in-app. Tabla simple: una fila por
-- notificación individual (no agrupada), leído_en NULL = no leída.

CREATE TABLE notificaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario_id bigint NOT NULL REFERENCES miembros_equipo(id),
    tipo varchar(30) NOT NULL,
    mensaje varchar(500) NOT NULL,
    entidad_tipo varchar(20),
    entidad_id bigint,
    leido_en timestamptz,
    creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_notificaciones_destinatario ON notificaciones (destinatario_id, leido_en);
