-- ============================================================================
-- SOLO PARA PRUEBAS LOCALES. NO ejecutar contra la base de datos real de DOVELA:
-- ahí CLIENTES y EBA_DEMO_MD_PROJECTS YA EXISTEN (ver 00_ARCHIVOS/schema_existente.sql).
--
-- Recrea, sobre una Oracle local vacía (docker-compose), un subconjunto equivalente
-- del esquema legado de APEX que este módulo necesita, para poder levantar y probar
-- el worker de principio a fin sin tocar el ambiente productivo.
--
-- El runner de scripts de la imagen gvenzl/oracle-free conecta cada archivo con
-- `sqlplus / as sysdba`, lo que por default cae en el contenedor CDB$ROOT y en el
-- esquema SYS. Sin las dos líneas siguientes, todo este script (y los DDL reales que
-- se incluyen al final) terminaría creando las tablas en el lugar equivocado, donde
-- la app (que se conecta como PORTAL_APP contra FREEPDB1) nunca las vería.
-- ============================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = PORTAL_APP;

CREATE TABLE CLIENTES (
  ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL ENABLE,
  NOMBRE      VARCHAR2(200 CHAR),
  DESCRIPCION VARCHAR2(4000 CHAR),
  CONSTRAINT CLIENTES_PK PRIMARY KEY (ID) USING INDEX ENABLE
);

CREATE TABLE EBA_DEMO_MD_TEAM_MEMBERS (
  ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL ENABLE,
  NOMBRE VARCHAR2(255),
  CONSTRAINT EBA_DEMO_MD_TEAM_MEMBERS_PK PRIMARY KEY (ID) USING INDEX ENABLE
);

CREATE TABLE EBA_DEMO_MD_STATUS (
  CD          VARCHAR2(15) NOT NULL ENABLE,
  DESCRIPCION VARCHAR2(200),
  CONSTRAINT EBA_DEMO_MD_STATUS_PK PRIMARY KEY (CD) USING INDEX ENABLE
);

INSERT INTO EBA_DEMO_MD_STATUS (CD, DESCRIPCION) VALUES ('EN ESPERA', 'En espera');

CREATE TABLE EBA_DEMO_MD_PROJECTS (
  ID              NUMBER NOT NULL ENABLE,
  PROJECT_LEAD    NUMBER,
  NAME            VARCHAR2(255) NOT NULL ENABLE,
  DESCRIPTION     VARCHAR2(4000),
  STATUS_CD       VARCHAR2(15) NOT NULL ENABLE,
  COMPLETED_DATE  DATE,
  CREATED         TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
  CREATED_BY      VARCHAR2(255) NOT NULL ENABLE,
  UPDATED         TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
  UPDATED_BY      VARCHAR2(255) NOT NULL ENABLE,
  CLIENTE         VARCHAR2(100),
  ORDEN_PRIORIDAD VARCHAR2(100),
  TIPO            VARCHAR2(100),
  CONSTRAINT EBA_DEMO_MD_PROJECTS_PK PRIMARY KEY (ID) USING INDEX ENABLE,
  CONSTRAINT EBA_DEMO_MD_PROJECTS_UK UNIQUE (NAME) USING INDEX ENABLE
);

ALTER TABLE EBA_DEMO_MD_PROJECTS ADD CONSTRAINT EBA_DEMO_MD_TEAM_MEMBER_FK FOREIGN KEY (PROJECT_LEAD)
  REFERENCES EBA_DEMO_MD_TEAM_MEMBERS (ID) ON DELETE SET NULL ENABLE;
ALTER TABLE EBA_DEMO_MD_PROJECTS ADD CONSTRAINT EBA_DEMO_MD_STATUS_FK FOREIGN KEY (STATUS_CD)
  REFERENCES EBA_DEMO_MD_STATUS (CD) ON DELETE SET NULL ENABLE;

-- Igual que el trigger real, salvo que usa USER en vez de wwv_flow.g_user (no hay
-- sesión de Oracle APEX en esta BD local de pruebas).
CREATE OR REPLACE TRIGGER BIU_EBA_DEMO_MD_PROJECTS
  BEFORE INSERT OR UPDATE ON EBA_DEMO_MD_PROJECTS
  FOR EACH ROW
BEGIN
  IF :new.id IS NULL THEN
    :new.id := TO_NUMBER(SYS_GUID(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
  END IF;
  IF INSERTING THEN
    :new.created    := CURRENT_TIMESTAMP;
    :new.created_by := USER;
  END IF;
  :new.updated    := CURRENT_TIMESTAMP;
  :new.updated_by := USER;
END;
/

-- Aplica los DDL reales del roadmap sobre este mismo esquema/sesión (CONTAINER y
-- CURRENT_SCHEMA ya quedaron fijados arriba). Se montan fuera de
-- /container-entrypoint-initdb.d/ (ver docker-compose.yml) para que el runner de la
-- imagen no los vuelva a ejecutar por separado como una sesión SYS/CDB$ROOT nueva.
@@/opt/oracle/local_test_includes/001_modulo_1_1_ddl.sql
@@/opt/oracle/local_test_includes/002_modulo_1_2_ddl.sql
