-- ============================================================================
-- Módulo 1.1 — Ingestión de Solicitudes por Correo Electrónico
-- ============================================================================
-- Este script se ejecuta UNA VEZ contra la base de datos REAL de DOVELA, donde
-- CLIENTES y EBA_DEMO_MD_PROJECTS ya existen (ver 00_ARCHIVOS/schema_existente.sql).
-- NO recrea esas tablas: solo agrega lo mínimo que este módulo necesita.
--
-- Para pruebas locales contra una BD Oracle vacía, usar en su lugar
-- 000_local_test_seed.sql (recrea un subconjunto equivalente del esquema legado)
-- seguido de este mismo script.
-- ============================================================================

-- 1) EBA_DEMO_MD_PROJECTS no tenía columna para el email del remitente.
ALTER TABLE EBA_DEMO_MD_PROJECTS ADD (SOLICITANTE_EMAIL VARCHAR2(320));

-- 2) Adjuntos guardados en el NFS (real o simulado).
CREATE TABLE ADJUNTOS (
  ID                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  NOMBRE_ARCHIVO       VARCHAR2(500) NOT NULL,
  RUTA_ALMACENAMIENTO  VARCHAR2(1000) NOT NULL,
  TIPO_MIME            VARCHAR2(150),
  TAMANO_BYTES         NUMBER,
  FECHA_CARGA          DATE DEFAULT SYSDATE NOT NULL
);

-- 3) Relación N:M solicitud-adjunto.
CREATE TABLE SOLICITUDES_ADJUNTOS (
  ID_SOLICITUD NUMBER NOT NULL,
  ID_ADJUNTO   NUMBER NOT NULL,
  CONSTRAINT SOLICITUDES_ADJUNTOS_PK PRIMARY KEY (ID_SOLICITUD, ID_ADJUNTO),
  CONSTRAINT SA_SOLICITUD_FK FOREIGN KEY (ID_SOLICITUD) REFERENCES EBA_DEMO_MD_PROJECTS(ID),
  CONSTRAINT SA_ADJUNTO_FK FOREIGN KEY (ID_ADJUNTO) REFERENCES ADJUNTOS(ID)
);

CREATE INDEX IDX_SOLICITUDES_ADJ_ADJUNTO ON SOLICITUDES_ADJUNTOS(ID_ADJUNTO);

-- 4) Documento .md generado por solicitud (1:1).
CREATE TABLE SOLICITUDES_MD (
  ID_SOLICITUD     NUMBER NOT NULL,
  RUTA_MD          VARCHAR2(1000) NOT NULL,
  FECHA_GENERACION DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT SOLICITUDES_MD_PK PRIMARY KEY (ID_SOLICITUD),
  CONSTRAINT SMD_SOLICITUD_FK FOREIGN KEY (ID_SOLICITUD) REFERENCES EBA_DEMO_MD_PROJECTS(ID)
);

-- 5) Deduplicación de correos ya procesados (idempotencia del worker ante reinicios).
CREATE TABLE EMAILS_PROCESADOS (
  ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  EMAIL_MESSAGE_ID VARCHAR2(998) NOT NULL,
  ID_SOLICITUD     NUMBER,
  FECHA_PROCESADO  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT EMAILS_PROCESADOS_UK UNIQUE (EMAIL_MESSAGE_ID),
  CONSTRAINT EP_SOLICITUD_FK FOREIGN KEY (ID_SOLICITUD) REFERENCES EBA_DEMO_MD_PROJECTS(ID)
);

-- ============================================================================
-- IMPORTANTE: el worker inserta siempre STATUS_CD = 'EN ESPERA'. Verificar que ese
-- código exista en EBA_DEMO_MD_STATUS antes de correr el worker contra esta BD real
-- (la FK EBA_DEMO_MD_STATUS_FK de EBA_DEMO_MD_PROJECTS rechazará el INSERT si no existe):
--
--   SELECT CD FROM EBA_DEMO_MD_STATUS WHERE CD = 'EN ESPERA';
--
-- Si no aparece, debe darse de alta en el catálogo antes de poner el worker en marcha.
-- ============================================================================
